version: "3.7"

volumes:
    db-volume:

services:
    server:
        build:
            context: .
            target: dev
        container_name: discord_clone_server
        volumes:
            - ./:/app
        env_file:
            - .env
        ports:
            - "3000:3000"

# App services
    db:
        image: mysql:5.7
        container_name: discord_clone_db
        environment:
            MYSQL_DATABASE: discord_clone
            MYSQL_ROOT_PASSWORD: secret
        ports:
        - "3306:3306"
        volumes:
        - db-volume:/var/lib/mysql
    redis:
        image: 'bitnami/redis:latest'
        environment: 
            - REDIS_PASSWORD=secret
            - ALLOW_EMPTY_PASSWORD=yes
