version: "3.7"

volumes:
    db-volume:

services:
    server:
        build:
            context: .
            target: dev
        volumes:
            - ./:/app
        environment: 
            WAIT_HOSTS: db:3306
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: discord_clone
        ports:
        - "3306:3306"
        volumes:
        - db-volume:/var/lib/mysql